# ============================================================
# Qutebrowser Config — Clean Dark Minimal Setup
# ============================================================

# -------------------------
# Core Behavior
# -------------------------

c.url.searchengines = {
    "DEFAULT": "https://search.brave.com/search?q={}"
}

c.content.headers.user_agent = (
    "Mozilla/5.0 (X11; Linux x86_64) "
    "AppleWebKit/537.36 "
    "Chrome/120.0.0.0 Safari/537.36"
)

c.auto_save.session = True
c.session.lazy_restore = True


# -------------------------
# UI — Tabs (Brave-like)
# -------------------------

# Tab bar background
c.colors.tabs.bar.bg = "#000000"

# Inactive tabs
c.colors.tabs.even.bg = "#000000"
c.colors.tabs.odd.bg = "#000000"
c.colors.tabs.even.fg = "#777777"
c.colors.tabs.odd.fg = "#777777"

# Active tab (subtle highlight)
c.colors.tabs.selected.even.bg = "#1f1f1f"
c.colors.tabs.selected.odd.bg = "#1f1f1f"
c.colors.tabs.selected.even.fg = "#ffffff"
c.colors.tabs.selected.odd.fg = "#ffffff"


# -------------------------
# Optional UI polish
# -------------------------

c.colors.completion.category.bg = "#111111"
c.colors.completion.even.bg = "#0d0d0d"
c.colors.completion.odd.bg = "#0d0d0d"
c.colors.completion.fg = "#cccccc"

c.colors.statusbar.normal.bg = "#000000"
c.colors.statusbar.insert.bg = "#111111"
c.colors.statusbar.command.bg = "#111111"

c.tabs.padding = {"top": 6, "bottom": 6, "left": 10, "right": 10}
c.tabs.min_width = 150
c.tabs.max_width = 220
c.tabs.indicator.width = 0

# -------------------------
# Load autogenerated config
# -------------------------

config.load_autoconfig()
