# Font
font_family JetBrainsMono Nerd Font
font_size 12.0

# Cursor
cursor_shape beam
cursor_blink_interval 0.95

# Scrollback
scrollback_lines 10000

# Window
window_padding_width 8
background_opacity 0.7

# Colors (nice dark theme)
foreground #cdd6f4
background #1e1e2e

# Tabs
tab_bar_edge top

# Performance
enable_audio_bell no

# keymappings
map ctrl+/ send_text all \x1f

# Ctrl+Enter
map ctrl+enter send_text all \x1b[13;5u
# Ctrl+Shift+Enter
map ctrl+shift+enter send_text all \x1b[13;6u

# Ctrl+Shift+Left
map ctrl+shift+left send_text all \x1b[1;6D
# Ctrl+Shift+Right
map ctrl+shift+right send_text all \x1b[1;6C
